name: 'Cache'

on: [push]
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Cache node module
        id: cache-step
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-cache-file-&{{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-cache-file-
            ${{ runner.os }}-
      - name: Display cache
        run: echo '${{ toJSON(steps.cache-step.outputs) }}'
      - name: Install node
        run: npm install