name: docker_wf

on: [push]

jobs:
  test_docker_cont:
    runs-on: ubuntu-latest
    container:
      image: node:12
      env:
        NODE_ENV: Dev
      ports:
        - 80
      volumes:
        - docker_volumes:/volumes
      options: --cpus 1

    steps:
      - name: Display node ver
        run: node -v
