name: first_fw

on: [push]

jobs:
  run-1-command:
    runs-on: ubuntu-latest
    steps:
      - name: Display some text
        run: echo "some text"
      - name: MultyStep
        run: |
          which python
          node -v