name: first_fw

on: [push]

jobs:
  run-first-command:
    runs-on: ubuntu-latest
    steps:
      - name: Display some text
        run: echo "some text"
      - name: MultyStep
        run: |
          python -version
          node -v