name: wf_3

on:
  pull_request:
    types:
      [assigned, edited]


jobs:
  run-3-command:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: List files
        run: ls -l