name: wf_3

on: [push]

jobs:
  run-3-command:
    runs-on: ubuntu-latest
    steps:
      - name: Copy repo to station
        run: |
          git config --global init.defaultBranch "main"
          git init
          git remote add origin "https://$GITHUB_ACTOR:${{secrets.GITHUB_TOKEN}}@github.com
          git fetch origin
          git checkout main
      - name: List files
        run: ls -l