name: wf_3

on: [push]

jobs:
  run-3-command:
    runs-on: ubuntu-latest
    steps:
      - name: Copy repo to station
        run: |
          git clone "https://github.com/dpfchel/python_training.git"
          git checkout main
      - name: List files
        run: ls -l